# Generated by Django 3.1.1 on 2023-05-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinionminer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
