# Generated by Django 3.2 on 2023-06-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinionminer', '0003_opinion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
