# Generated by Django 3.2 on 2023-06-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinionminer', '0006_remove_opinion_noun_phrases'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
