# Generated by Django 3.2 on 2023-06-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinionminer', '0007_opinion_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='total_sentiment_strength',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
